apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-dependencies
  namespace: dify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-conf
  namespace: dify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi