apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: dify
  labels:
    app: sandbox
    component: executor
spec:
  type: ClusterIP
  ports:
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: sandbox
  selector:
    app: sandbox
    component: executor