apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: dify
  labels:
    app: web
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: web
  selector:
    app: web
    component: frontend