apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: dify
  labels:
    app: api
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: api
  selector:
    app: api
    component: backend