apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugin-storage
  namespace: dify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi