apiVersion: v1
kind: Service
metadata:
  name: ssrf-proxy
  namespace: dify
  labels:
    app: ssrf-proxy
    component: proxy
spec:
  type: ClusterIP
  ports:
  - port: 3128
    targetPort: 3128
    protocol: TCP
    name: proxy
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: reverse-proxy
  selector:
    app: ssrf-proxy
    component: proxy