apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-config
  namespace: dify
data:
  # API URLs
  CONSOLE_API_URL: ""
  CONSOLE_WEB_URL: ""
  SERVICE_API_URL: ""
  APP_API_URL: ""
  APP_WEB_URL: ""
  FILES_URL: ""
  
  # Logging
  LOG_LEVEL: "INFO"
  LOG_FILE: "/app/logs/server.log"
  LOG_FILE_MAX_SIZE: "20"
  LOG_FILE_BACKUP_COUNT: "5"
  LOG_DATEFORMAT: "%Y-%m-%d %H:%M:%S"
  LOG_TZ: "UTC"
  DEBUG: "false"
  FLASK_DEBUG: "false"
  ENABLE_REQUEST_LOGGING: "False"
  
  # Environment
  DEPLOY_ENV: "PRODUCTION"
  CHECK_UPDATE_URL: "https://updates.dify.ai"
  OPENAI_API_BASE: "https://api.openai.com/v1"
  MIGRATION_ENABLED: "true"
  
  # Security
  FILES_ACCESS_TIMEOUT: "300"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  REFRESH_TOKEN_EXPIRE_DAYS: "30"
  
  # Server Configuration
  APP_MAX_ACTIVE_REQUESTS: "0"
  APP_MAX_EXECUTION_TIME: "1200"
  DIFY_BIND_ADDRESS: "0.0.0.0"
  DIFY_PORT: "5001"
  SERVER_WORKER_AMOUNT: "1"
  SERVER_WORKER_CLASS: "gevent"
  SERVER_WORKER_CONNECTIONS: "10"
  CELERY_WORKER_CLASS: ""
  GUNICORN_TIMEOUT: "360"
  CELERY_WORKER_AMOUNT: ""
  CELERY_AUTO_SCALE: "false"
  CELERY_MAX_WORKERS: ""
  CELERY_MIN_WORKERS: ""
  
  # API Tool Configuration
  API_TOOL_DEFAULT_CONNECT_TIMEOUT: "10"
  API_TOOL_DEFAULT_READ_TIMEOUT: "60"
  ENABLE_WEBSITE_JINAREADER: "true"
  ENABLE_WEBSITE_FIRECRAWL: "true"
  ENABLE_WEBSITE_WATERCRAWL: "true"
  
  # Database
  DB_USERNAME: "postgres"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_DATABASE: "dify"
  SQLALCHEMY_POOL_SIZE: "30"
  SQLALCHEMY_POOL_RECYCLE: "3600"
  SQLALCHEMY_ECHO: "false"
  
  # PostgreSQL Configuration
  POSTGRES_MAX_CONNECTIONS: "100"
  POSTGRES_SHARED_BUFFERS: "128MB"
  POSTGRES_WORK_MEM: "4MB"
  POSTGRES_MAINTENANCE_WORK_MEM: "64MB"
  POSTGRES_EFFECTIVE_CACHE_SIZE: "4096MB"
  
  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_USERNAME: ""
  REDIS_USE_SSL: "false"
  REDIS_DB: "0"
  REDIS_USE_SENTINEL: "false"
  REDIS_SENTINELS: ""
  REDIS_SENTINEL_SERVICE_NAME: ""
  REDIS_SENTINEL_USERNAME: ""
  REDIS_SENTINEL_SOCKET_TIMEOUT: "0.1"
  REDIS_USE_CLUSTERS: "false"
  REDIS_CLUSTERS: ""
  
  # Celery
  CELERY_BROKER_URL: "redis://:difyai123456@redis:6379/1"
  BROKER_USE_SSL: "false"
  CELERY_USE_SENTINEL: "false"
  CELERY_SENTINEL_MASTER_NAME: ""
  CELERY_SENTINEL_SOCKET_TIMEOUT: "0.1"
  
  # CORS
  WEB_API_CORS_ALLOW_ORIGINS: "*"
  CONSOLE_CORS_ALLOW_ORIGINS: "*"
  
  # Storage
  STORAGE_TYPE: "opendal"
  OPENDAL_SCHEME: "fs"
  OPENDAL_FS_ROOT: "storage"
  
  # Vector Store
  VECTOR_STORE: "weaviate"
  WEAVIATE_ENDPOINT: "http://weaviate:8080"
  
  # File Upload
  UPLOAD_FILE_SIZE_LIMIT: "15"
  UPLOAD_FILE_BATCH_LIMIT: "5"
  UPLOAD_IMAGE_FILE_SIZE_LIMIT: "10"
  UPLOAD_VIDEO_FILE_SIZE_LIMIT: "100"
  UPLOAD_AUDIO_FILE_SIZE_LIMIT: "50"
  
  # ETL
  ETL_TYPE: "dify"
  UNSTRUCTURED_API_URL: ""
  SCARF_NO_ANALYTICS: "true"
  
  # Generation
  PROMPT_GENERATION_MAX_TOKENS: "512"
  CODE_GENERATION_MAX_TOKENS: "1024"
  PLUGIN_BASED_TOKEN_COUNTING_ENABLED: "false"
  MULTIMODAL_SEND_FORMAT: "base64"
  
  # Notion
  NOTION_INTEGRATION_TYPE: "public"
  
  # Mail
  MAIL_TYPE: "resend"
  RESEND_API_URL: "https://api.resend.com"
  SMTP_PORT: "465"
  SMTP_USE_TLS: "true"
  SMTP_OPPORTUNISTIC_TLS: "false"
  
  # Indexing
  INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: "4000"
  INVITE_EXPIRY_HOURS: "72"
  RESET_PASSWORD_TOKEN_EXPIRY_MINUTES: "5"
  
  # Code Execution
  CODE_EXECUTION_ENDPOINT: "http://sandbox:8194"
  CODE_MAX_NUMBER: "9223372036854775807"
  CODE_MIN_NUMBER: "-9223372036854775808"
  CODE_MAX_DEPTH: "5"
  CODE_MAX_PRECISION: "20"
  CODE_MAX_STRING_LENGTH: "80000"
  CODE_MAX_STRING_ARRAY_LENGTH: "30"
  CODE_MAX_OBJECT_ARRAY_LENGTH: "30"
  CODE_MAX_NUMBER_ARRAY_LENGTH: "1000"
  CODE_EXECUTION_CONNECT_TIMEOUT: "10"
  CODE_EXECUTION_READ_TIMEOUT: "60"
  CODE_EXECUTION_WRITE_TIMEOUT: "10"
  
  # Workflow
  TEMPLATE_TRANSFORM_MAX_LENGTH: "80000"
  WORKFLOW_MAX_EXECUTION_STEPS: "500"
  WORKFLOW_MAX_EXECUTION_TIME: "1200"
  WORKFLOW_CALL_MAX_DEPTH: "5"
  MAX_VARIABLE_SIZE: "204800"
  WORKFLOW_PARALLEL_DEPTH_LIMIT: "3"
  WORKFLOW_FILE_UPLOAD_LIMIT: "10"
  WORKFLOW_NODE_EXECUTION_STORAGE: "rdbms"
  
  # HTTP Request
  HTTP_REQUEST_NODE_MAX_BINARY_SIZE: "10485760"
  HTTP_REQUEST_NODE_MAX_TEXT_SIZE: "1048576"
  HTTP_REQUEST_NODE_SSL_VERIFY: "True"
  RESPECT_XFORWARD_HEADERS_ENABLED: "false"
  SSRF_PROXY_HTTP_URL: "http://ssrf_proxy:3128"
  SSRF_PROXY_HTTPS_URL: "http://ssrf_proxy:3128"
  
  # Limits
  LOOP_NODE_MAX_COUNT: "100"
  MAX_TOOLS_NUM: "10"
  MAX_PARALLEL_LIMIT: "10"
  MAX_ITERATIONS_NUM: "99"
  TEXT_GENERATION_TIMEOUT_MS: "60000"
  
  # Sandbox
  SANDBOX_GIN_MODE: "release"
  SANDBOX_WORKER_TIMEOUT: "15"
  SANDBOX_ENABLE_NETWORK: "true"
  SANDBOX_HTTP_PROXY: "http://ssrf_proxy:3128"
  SANDBOX_HTTPS_PROXY: "http://ssrf_proxy:3128"
  SANDBOX_PORT: "8194"
  
  # Plugin
  PLUGIN_DAEMON_PORT: "5002"
  PLUGIN_MAX_PACKAGE_SIZE: "52428800"
  PLUGIN_PPROF_ENABLED: "false"
  PLUGIN_DEBUGGING_HOST: "0.0.0.0"
  PLUGIN_DEBUGGING_PORT: "5003"
  PLUGIN_DIFY_INNER_API_URL: "http://api:5001"
  ENDPOINT_URL_TEMPLATE: "http://localhost/e/{hook_id}"
  MARKETPLACE_ENABLED: "true"
  MARKETPLACE_API_URL: "https://marketplace.dify.ai"
  FORCE_VERIFYING_SIGNATURE: "true"
  PLUGIN_PYTHON_ENV_INIT_TIMEOUT: "120"
  PLUGIN_MAX_EXECUTION_TIMEOUT: "600"
  PLUGIN_STORAGE_TYPE: "local"
  PLUGIN_STORAGE_LOCAL_ROOT: "/app/storage"
  PLUGIN_WORKING_PATH: "/app/storage/cwd"
  PLUGIN_INSTALLED_PATH: "plugin"
  PLUGIN_PACKAGE_CACHE_PATH: "plugin_packages"
  PLUGIN_MEDIA_CACHE_PATH: "assets"
  PLUGIN_S3_USE_AWS: "false"
  PLUGIN_S3_USE_AWS_MANAGED_IAM: "false"
  PLUGIN_S3_USE_PATH_STYLE: "false"
  PLUGIN_ALIYUN_OSS_AUTH_VERSION: "v4"
  
  # OTEL
  ENABLE_OTEL: "false"
  OTLP_BASE_ENDPOINT: "http://localhost:4318"
  OTEL_EXPORTER_TYPE: "otlp"
  OTEL_SAMPLING_RATE: "0.1"
  OTEL_BATCH_EXPORT_SCHEDULE_DELAY: "5000"
  OTEL_MAX_QUEUE_SIZE: "2048"
  OTEL_MAX_EXPORT_BATCH_SIZE: "512"
  OTEL_METRIC_EXPORT_INTERVAL: "60000"
  OTEL_BATCH_EXPORT_TIMEOUT: "10000"
  OTEL_METRIC_EXPORT_TIMEOUT: "30000"
  
  # Miscellaneous
  ALLOW_EMBED: "false"
  QUEUE_MONITOR_THRESHOLD: "200"
  QUEUE_MONITOR_INTERVAL: "30"
  EXPOSE_NGINX_PORT: "80"
  EXPOSE_NGINX_SSL_PORT: "443"
  EXPOSE_PLUGIN_DAEMON_PORT: "5002"
  EXPOSE_PLUGIN_DEBUGGING_HOST: "localhost"
  EXPOSE_PLUGIN_DEBUGGING_PORT: "5003"
  CREATE_TIDB_SERVICE_JOB_ENABLED: "false"
  MAX_SUBMIT_COUNT: "100"
  TOP_K_MAX_VALUE: "10"
  DB_PLUGIN_DATABASE: "dify_plugin"