apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-storage
  namespace: dify
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi